### ISSUE TITLE
The getter 'width' was called on null

### ISSUE THREAD

**Issue by amitkhairnar44** [hanshengchiu/reorderables#27]
Hello, I got this issue when I used ReorderableColumn inside the Stepper widget.
Stepper > Step > Form > Column > ReorderableColumn.
Whenever I long press the UI for dragging it produces this error:
```
flutter: The following assertion was thrown while handling a gesture:
flutter: ScrollController attached to multiple scroll views.
flutter: 'package:flutter/src/widgets/scroll_controller.dart':
flutter: Failed assertion: line 111 pos 12: '_positions.length == 1'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:111:12)
flutter: #3      ScrollController.offset (package:flutter/src/widgets/scroll_controller.dart:118:24)
flutter: #4      _ReorderableFlexContentState._scrollTo (package:reorderables/src/widgets/reorderable_flex.dart:353:51)
flutter: #5      _ReorderableFlexContentState._wrap.<anonymous closure>.<anonymous closure> (package:reorderables/src/widgets/reorderable_flex.dart:722:11)
flutter: #6      _DragTargetState.didEnter (package:flutter/src/widgets/drag_target.dart)
flutter: #7      _DragAvatar.updateDrag.<anonymous closure> (package:flutter/src/widgets/drag_target.dart:658:23)
flutter: #8      _ListBase&Object&ListMixin.firstWhere (dart:collection/list.dart:137:15)
flutter: #9      _DragAvatar.updateDrag (package:flutter/src/widgets/drag_target.dart:655:51)
flutter: #10     new _DragAvatar (package:flutter/src/widgets/drag_target.dart:591:5)
flutter: #11     _DraggableState._startDrag (package:flutter/src/widgets/drag_target.dart:381:35)
flutter: #12     LongPressDraggable.createRecognizer.<anonymous closure> (package:flutter/src/widgets/drag_target.dart:319:36)
flutter: #13     MultiDragGestureRecognizer._startDrag.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:266:52)
flutter: #14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:181:24)
flutter: #15     MultiDragGestureRecognizer._startDrag (package:flutter/src/gestures/multidrag.dart:266:14)
flutter: #16     MultiDragGestureRecognizer.acceptGesture.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:256:48)
flutter: #17     _DelayedPointerState.accepted (package:flutter/src/gestures/multidrag.dart:485:14)
flutter: #18     MultiDragGestureRecognizer.acceptGesture (package:flutter/src/gestures/multidrag.dart:256:11)
flutter: #19     GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:263:12)
flutter: #20     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:222:9)
flutter: #21     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:52:12)
flutter: #22     MultiDragPointerState.resolve (package:flutter/src/gestures/multidrag.dart:62:17)
flutter: #23     _DelayedPointerState._delayPassed (package:flutter/src/gestures/multidrag.dart:471:7)
flutter: #32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
flutter: (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
flutter:
flutter: Handler: "onStart"
flutter: Recognizer:
flutter:   DelayedMultiDragGestureRecognizer#0bd37
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The getter 'width' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'width' was called on null.
```

**Comment by Nico04** [comment]
I've got the same issue (with ReorderableColumn) with a more complexe project, but I found out that it occurs only when there are other scroll widget in the tree.
Weither it's a ListView, a SingleChildScrollView...

I've edited the end of your ColumnExample2 to help you fix this issue :

`    return Material(
      child: Card(
        child: Column(
          children: <Widget>[
            reorderableColumn,
            SingleChildScrollView(
              child: Text('r'),
            )
          ],
        )
      ),
      elevation: 6.0,
      color: Colors.transparent,
      borderRadius: BorderRadius.zero,
    );`

**Comment by Nico04** [comment]
I've juste realized that the same error (ScrollController attached to multiple scroll views) happens in the same way with Flutter/ReorderableListView.

This may help you resolve it
https://github.com/flutter/flutter/pull/31666

**Comment by amitkhairnar44** [comment]
@Nico04 Thank you for explaining this. Waiting for the pull request to get merged

**Comment by Nico04** [comment]
Unfortunately I will not take the time to make a pull request, if that's what you were waiting for, I'll wait for your bugfix.
Thanks 😉

**Comment by Nico04** [comment]
I found a workaround : just assign a new ScrollController to the scrollController parameter :
`ReorderableColumn(
  scrollController: ScrollController()
)`

**Comment by kwent** [comment]
@hanshengchiu Still happening on https://github.com/hanshengchiu/reorderables/commit/56578adc64d9a924ba82b129c2dac788ceddd016 even after https://github.com/hanshengchiu/reorderables/pull/48

**Comment by harjindersinghbobby** [comment]
> I found a workaround : just assign a new ScrollController to the scrollController parameter :
> `ReorderableColumn( scrollController: ScrollController() )`

thanks this works for me
