### ISSUE TITLE
The example is not working

### ISSUE THREAD

**Issue by crizant** [hanshengchiu/reorderables#82]
Hi, I tried to run the example on iOS simulator, here is the output:

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: BoxConstraints has non-normalized width constraints.
flutter: These invalid constraints were provided to RenderTabluarFlex's layout() function by the following
flutter: function, which probably computed the invalid constraints in question:
flutter:   RenderTabluarFlex.performLayout (package:reorderables/src/rendering/tabluar_flex.dart:731:28)
flutter: The offending constraints were:
flutter:   BoxConstraints(384.0<=w<=375.0, 0.0<=h<=Infinity; NOT NORMALIZED)
flutter:
flutter: The relevant error-causing widget was:
flutter:   TabluarFlex-[GlobalKey#57296 ReorderableTable table key]
flutter:   file:///Users/crizant/Documents/reorderables/lib/src/widgets/reorderable_table.dart:203:18
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:519:9)
flutter: #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:554:19)
flutter: #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:567:6)
flutter: #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1678:24)
flutter: #4      RenderTabluarFlex.performLayout (package:reorderables/src/rendering/tabluar_flex.dart:731:28)
flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #6      _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:544:13)
flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #20     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #24     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
flutter: #25     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:498:7)
flutter: #26     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
flutter: #27     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
flutter: #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #32     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1304:11)
flutter: #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #40     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
flutter: #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #53     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3263:13)
flutter: #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #57     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
flutter: #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #71     RenderView.performLayout (package:flutter/src/rendering/view.dart:171:13)
flutter: #72     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1638:7)
flutter: #73     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:896:18)
flutter: #74     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:403:19)
flutter: #75     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:881:13)
flutter: #76     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #77     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1114:15)
flutter: #78     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1053:9)
flutter: #79     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
flutter: (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderTabluarFlex#d38a2 relayoutBoundary=up10 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   creator: TabluarFlex-[GlobalKey#57296 ReorderableTable table key] ← _SingleChildViewport ←
flutter:     IgnorePointer-[GlobalKey#4eeda] ← Semantics ← _PointerListener ← Listener ← _GestureSemantics ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#30746] ← _PointerListener ← Listener
flutter:     ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#2572f] ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=Infinity)
flutter:   size: MISSING
flutter:   direction: vertical
flutter:   mainAxisAlignment: start
flutter:   mainAxisSize: max
flutter:   crossAxisAlignment: center
flutter:   verticalDirection: down
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child 1: RenderTabluarFlex#9e869 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child 1: RenderParagraph#4d6f9 relayoutBoundary=up12 NEEDS-PAINT
flutter:         text: TextSpan
flutter:       child 2: RenderParagraph#80f0d relayoutBoundary=up12 NEEDS-PAINT
flutter:         text: TextSpan
flutter:       child 3: RenderParagraph#c833e relayoutBoundary=up12 NEEDS-PAINT
flutter:         text: TextSpan
flutter:       child 4: RenderParagraph#ddd09 relayoutBoundary=up12 NEEDS-PAINT
flutter:         text: TextSpan
flutter:       child 5: RenderParagraph#7133b relayoutBoundary=up12 NEEDS-PAINT
flutter:         text: TextSpan
flutter:     child 2: RenderFlex#7c04f relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child 1: RenderMetaData#99f13 relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child: RenderPointerListener#34d9a relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderMetaData#d6288 relayoutBoundary=up14 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderMergeSemantics#6e775 relayoutBoundary=up15 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:     child 3: RenderFlex#264be relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child 1: RenderMetaData#09995 relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child: RenderPointerListener#b7b5d relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderMetaData#d98d7 relayoutBoundary=up14 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderMergeSemantics#3bb2e relayoutBoundary=up15 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:     child 4: RenderFlex#c94cd relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child 1: RenderMetaData#c9e3d relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child: RenderPointerListener#33d1d relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderMetaData#1b397 relayoutBoundary=up14 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderMergeSemantics#42474 relayoutBoundary=up15 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RenderBox was not laid out: RenderTabluarFlex#d38a2 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderSingleChildViewport#586a7 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#bf28e relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#35c5e relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#13831 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#53777 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#4ff0a relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#a2ced relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderStack#6d2d7 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderTheatre#8949a relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderSingleChildViewport#586a7 relayoutBoundary=up9 NEEDS-PAINT
flutter: Another exception was thrown: Updated layout information required for RenderStack#9c459 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
flutter: Another exception was thrown: Bad state: Future already completed
```

flutter version:
```
Flutter 1.21.0-6.0.pre.160 • channel master • https://github.com/flutter/flutter.git
Framework • revision 31ee51a302 (6 hours ago) • 2020-08-03 17:27:21 -0700
Engine • revision fa16c3d0ba
Tools • Dart 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)
```

**Comment by hanshengchiu** [comment]
Could you try stable channel?
